from enum import Enum


class STATUS(Enum):
    STOP = 1
    CONTINUE = 2


class STATE(Enum):
    WAIT_FOR_ID = "WAIT_FOR_ID"
    WAIT_FOR_RESOLUTION = " WAIT_FOR_RESOLUTION"
    WAIT_FOR_AUDIO = "WAIT_FOR_AUDIO"
    WAIT_FOR_START_DOWNLOADING = "WAIT_FOR_START_DOWNLOADING"
    WAIT_FOR_DOWNLOAD = "WAIT_FOR_DOWNLOAD"
